logging:
  level:
    root: error
    com.mishinyura.booksmaven: debug
#  file:
#    name: logs/application.log

spring:
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 5
      connection-timeout: 20000
  #      schema: schema.sql
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
