--liquibase formatted sql

--changeset mishinyura:1
drop table if exists books;

create table books
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    enabled boolean not null default false
);

--rollback DROP TABLE books;
