--liquibase formatted sql

--changeset mishinyura:1
drop table if exists books;

create table books
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL
);

--rollback DROP TABLE books;
