--liquibase formatted sql

--changeset mishinyura:1
create table if not exists books
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL
);

--rollback DROP TABLE books;
